name: Run MATLAB Tests on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ubunts-latest
    steps:
     -name: Check out repository
      uses: actions/checkout@v4